project:
  type: website
    
website:
  site-url: https://jafhp.github.io/about.html
  repo-url: https://github.com/jaFHP/jaFHP.github.io/
  favicon: favicon.png
  title: "Jana"
  navbar:
    left:
      - text: "My research"
        href: index.qmd
      - text: "About me"
        href: about.qmd
      - text: "The Report"
      - href: assets/report.qmd

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true
    link-external-newwindow: true

execute:
  freeze: auto
  
